### ISSUE TITLE
SSR服务端无法通过cymysql远程连接数据库

### ISSUE THREAD

**Issue by YueYueYue** [esdeathlove/shadowsocks#38]
场景是这样的：A服务器上装载了前端和数据库，B/C/D/E服务器都是节点，只安装SSR后端，通过远程访问A的数据库。其中，B/C/D都可以正常访问并且使用，只有E不行。

自我排查：A的防火墙3306端口已开启；A的Mysql已经给予远程访问的权限；my.cnf配置文件修改了跳过域名解析和忽视大小写。

E的SSR运行后，给出的错误是这样的：

root@server1:~/shadowsocks# python server.py
loaded collections.OrderedDict
IPv6 support
2017-01-25 11:11:26 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2017-01-25 11:11:26 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-01-25 11:11:26 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-01-25 11:12:26 INFO     auto_block.py:66 Read hosts.deny from line 1383
2017-01-25 11:12:27 ERROR    db_transfer.py:669 Traceback (most recent call last):
  File "/root/shadowsocks/db_transfer.py", line 662, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/root/shadowsocks/db_transfer.py", line 272, in pull_db_all_user
    cur.execute("SELECT " + ','.join(keys) + " FROM user WHERE `class`>="+ str(nodeinfo[1]) + " " + node_group_sql + " AND`enable`=1 AND `expire_in`>now() AND `transfer_enable`>`u`+`d`")
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 116, in errorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))

曾经我遇到过类似的问题，也发过issue。回复是网络问题。确实，我把数据库换了一个VPS放就解决了。然而这次不行！

数据库在A无法使用，那我就更换到B/C，同样的设置，开启各种端口和权限，但是运行SSR给出的错误提示是完全一样的，就是上面这一段。

最后，我在E服务器直接安装了mysql-server，然后在mysql远程访问位于A的数据库，完全没有问题！可以show tables，可以查找行，给出的结果也都完全正确！看来锅在cymysql这里？google了好多也没找到为什么。所以再发一次issue在这里，不知道能否帮忙解决？谢谢。祝新年快乐。

**Comment by esdeathlove** [comment]
将数据库超时调大些试试，上网找找。2017年1月25日 上午11:16，YueYueYue <notifications@github.com>写道：场景是这样的：A服务器上装载了前端和数据库，B/C/D/E服务器都是节点，只安装SSR后端，通过远程访问A的数据库。其中，B/C/D都可以正常访问并且使用，只有E不行。
自我排查：A的防火墙3306端口已开启；A的Mysql已经给予远程访问的权限；my.cnf配置文件修改了跳过域名解析和忽视大小写。
E的SSR运行后，给出的错误是这样的：
root@server1:~/shadowsocks# python server.py
loaded collections.OrderedDict
IPv6 support
2017-01-25 11:11:26 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2017-01-25 11:11:26 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-01-25 11:11:26 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-01-25 11:12:26 INFO     auto_block.py:66 Read hosts.deny from line 1383
2017-01-25 11:12:27 ERROR    db_transfer.py:669 Traceback (most recent call last):
File "/root/shadowsocks/db_transfer.py", line 662, in thread_db
rows = db_instance.pull_db_all_user()
File "/root/shadowsocks/db_transfer.py", line 272, in pull_db_all_user
cur.execute("SELECT " + ','.join(keys) + " FROM user WHERE class>="+ str(nodeinfo[1]) + " " + node_group_sql + " ANDenable=1 AND expire_in>now() AND transfer_enable>u+d")
File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
self.errorhandler(exc, value)
File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
self.connection.errorhandler(self, errorclass, errorvalue)
File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 116, in errorhandler
raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))
曾经我遇到过类似的问题，也发过issue。回复是网络问题。确实，我把数据库换了一个VPS放就解决了。然而这次不行！
数据库在A无法使用，那我就更换到B/C，同样的设置，开启各种端口和权限，但是运行SSR给出的错误提示是完全一样的，就是上面这一段。
最后，我在E服务器直接安装了mysql-server，然后在mysql远程访问位于A的数据库，完全没有问题！可以show tables，可以查找行，给出的结果也都完全正确！看来锅在cymysql这里？google了好多也没找到为什么。所以再发一次issue在这里，不知道能否帮忙解决？谢谢。祝新年快乐。

**Comment by YueYueYue** [comment]
我调整了数据库所在的mysql超时设置，如下：

mysql> show variables like '%timeout';
+----------------------------+----------+
| Variable_name              | Value    |
+----------------------------+----------+
| connect_timeout            | 300      |
| delayed_insert_timeout     | 300      |
| innodb_lock_wait_timeout   | 50       |
| innodb_rollback_on_timeout | OFF      |
| interactive_timeout        | 28800    |
| lock_wait_timeout          | 31536000 |
| net_read_timeout           | 300      |
| net_write_timeout          | 300      |
| slave_net_timeout          | 3600     |
| wait_timeout               | 28800    |
+----------------------------+----------+
10 rows in set (0.00 sec)

然而并没有什么作用。运行python server.py后，仍然是报错，错误提示是一样的。

难道需要调整cymysql的timeout？这个我就不知道要怎么调了，google了没找到答案…………

**Comment by silentstage** [comment]
我也碰你这问题了，ABC3节点，A节点放SSpanel+后端，BC节点只装后端远程连接A，B和C都分别出现过这个问题，重启VPS就解决了

**Comment by vshen009** [comment]
我今天也遇到了 重启无解

2017-02-04 20:39:39 INFO     auto_block.py:66 Read hosts.deny from line 95244
2017-02-04 20:40:39 INFO     auto_block.py:66 Read hosts.deny from line 95246
2017-02-04 20:41:39 ERROR    db_transfer.py:692 Traceback (most recent call last):
  File "/home/shadowsocks/db_transfer.py", line 685, in thread_db
    rows = db_instance.pull_db_all_user()
  File "/home/shadowsocks/db_transfer.py", line 301, in pull_db_all_user
    cur.execute("SELECT " + ','.join(keys_detect) + " FROM detect_list where `type` = 1")
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 133, in execute
    self.errorhandler(exc, value)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/cursors.py", line 35, in errorhandler
    self.connection.errorhandler(self, errorclass, errorvalue)
  File "/usr/local/lib/python2.7/dist-packages/cymysql/connections.py", line 116, in errorhandler
    raise Error(errorclass, errorvalue)
Error: (<class 'socket.timeout'>, timeout('timed out',))

2017-02-04 20:41:39 INFO     auto_block.py:66 Read hosts.deny from line 95248
2017-02-04 20:42:17 INFO     util.py:85 loading libcrypto from libcrypto.so.1.0.0
2017-02-04 20:42:17 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
2017-02-04 20:42:17 INFO     asyncdns.py:324 dns server: [('8.8.8.8', 53), ('8.8.4.4', 53)]
root@iZt4ncvgp8ovbo1naxopcsZ:/home/shadowsocks#
