### ISSUE TITLE
git pull了以后，启动出错了

### ISSUE THREAD

**Issue by nickeyfff** [esdeathlove/shadowsocks#40]
使用 logrun.sh启动， 显示：

2017-02-05 09:29:38 ERROR    db_transfer.py:690 Traceback (most recent call last):
  File "/root/shadowsocksr/db_transfer.py", line 684, in thread_db
    db_instance.del_server_out_of_bound_safe(last_rows, rows)
  File "/root/shadowsocksr/db_transfer.py", line 506, in del_server_out_of_bound_safe
    cfg['ip_md5_salt'] = get_config().IP_MD5_SALT
AttributeError: 'module' object has no attribute 'IP_MD5_SALT'

**Comment by nickeyfff** [comment]
好吧，要加个配置。。

**Comment by HanC890** [comment]
请问是加啥配置？我也遇上这个问题了
